# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=32)),
                ('duration', models.IntegerField(default=0)),
                ('serves', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=2014)),
            ],
        ),
    ]
