# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160711_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingitem',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='checked',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredientshop',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_ingredients', to='api.Shop'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='api.Recipe'),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Ingredient'),
        ),
    ]
