# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161003_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientshop',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Shop'),
        ),
    ]
