# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20161113_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.Shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredientshop',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientshop',
            name='shop',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='api.Ingredient'),
        ),
        migrations.DeleteModel(
            name='IngredientShop',
        ),
        migrations.AddField(
            model_name='ingredientlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.Location'),
        ),
    ]
