# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-22 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170420_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
