# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-15 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 15, 20, 14, 52, 915000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 15, 20, 15, 27, 400000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 15, 20, 15, 37, 162000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 15, 20, 15, 46, 514000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 15, 20, 16, 34, 554000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 15, 20, 16, 46, 753000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
